## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-grafana
  name: test-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-grafana
  template:
    metadata:
      labels:
        app: test-grafana
    spec:
      containers:
      - image: bitnami/grafana
        name: grafana
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-grafana
  name: test-grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-grafana
  sessionAffinity: None
  type: ClusterIP
